[package]
name = "rustboot"
version = "0.1.0"
authors = ["Twitter: @npashi <nihal.pasham@gmail.com>"]
edition = "2018"
categories = ["embedded", "no_std", "authentication"]
description = """
A platform agnostic, portable secure bootloader with firmware authentication 
and update capabilities, written in pure-Rust .
"""
documentation = ""
homepage = ""
keywords = ["security", "bootloader", "firmware", "authentication", "update"]
license = "Apache 2.0 or MIT"
readme = "README.md"
repository = ""
# Each example should have an explicit `[[example]]` section here to
# ensure that the correct features are enabled.
autoexamples = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = {version = "0.9.2", default-features = false}
k256 = {version = "0.9.0", features = ["ecdsa"]}
signature = {version = "1.3.0", default-features = false, features = ["digest-preview"]}
rustBoot-hal = {path = "../rustBoot-hal"}
# hex-literal = "0.3.1"

[features]
ext_flash = []
sha256 = []
sha384 = []
secp256k1 = ["sha256"]
ed25519 = ["sha256"]
default = ["sha256", "secp256k1"]

[[example]]
name = "nrf52840_example"
