[package]
name = "rustBoot-update"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustBoot = {path = "../../rustBoot"}
rustBoot-hal = {path = "../rustBoot-hal", default-features = false}