[workspace]

members = ["rustBoot-update",
           "rustBoot-hal", 
           "test_firmware/*/*", 
           "test_impls/*"
           ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "z"
panic = "abort"