[package]
name = "rustBoot-hal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nrf52840-hal = "0.13.0"
cortex-m = "0.7.3"

[features]
nrf = []
nrf52840 = ["nrf"]
default = ["nrf", "nrf52840"]