name: ci

on:
  push:
    branches: [mcusigner]
  pull_request:
    branches: [mcusigner]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check formatting
        run: cargo fmt -- --check

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - name: device-tree - unit tests
        run: |
          rustup install nightly
          cargo +nightly test --package rustBoot --lib -- --nocapture
      - name: rustBoot image parser - unit tests
        run: |
          cargo +nightly test --package rustBoot --lib --features nrf52840 -- parser::tests --nocapture
          cargo +nightly test --package rustBoot --lib --features stm32f411 -- parser::tests --nocapture
          cargo +nightly test --package rustBoot --lib --features stm32f446 -- parser::tests --nocapture
          cargo +nightly test --package rustBoot --lib --features stm32h723 -- parser::tests --nocapture
          cargo +nightly test --package rustBoot --lib --features stm32f746 -- parser::tests --nocapture
          cargo +nightly test --package rustBoot --lib --features stm32f334 -- parser::tests --nocapture
      - name: mcusigner - unit tests
        run: |
          cargo +nightly test --package rbsigner --bin rbsigner -- mcusigner::tests --nocapture


